services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: shelterDB
    ports:
      - "5432:5432"
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test1234
    ports:
      - "27017:27017"
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
